#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';
use SPORE::to::Swagger2 ();
use JSON::MaybeXS ();

my $spore = SPORE::to::Swagger2->new(shift);

binmode(STDOUT, ':utf8');
print JSON::MaybeXS->new(utf8 => 1, pretty => 1)->encode($spore->to_Swagger2);
